"""add_face_suggestions

Revision ID: 56f6544da217
Revises: 0ea4fdf7fc41
Create Date: 2025-12-25 17:11:00.399624

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56f6544da217'
down_revision: str | Sequence[str] | None = '0ea4fdf7fc41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('face_instance_id', sa.UUID(), nullable=False),
    sa.Column('suggested_person_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_face_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['face_instance_id'], ['face_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_face_id'], ['face_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_face_suggestions_face_instance_id', 'face_suggestions', ['face_instance_id'], unique=False)
    op.create_index('ix_face_suggestions_status', 'face_suggestions', ['status'], unique=False)
    op.create_index('ix_face_suggestions_suggested_person_id', 'face_suggestions', ['suggested_person_id'], unique=False)
    op.alter_column('face_instances', 'detection_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('face_instances', 'quality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_training_sessions_category_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_vector_deletion_logs_created_at'), table_name='vector_deletion_logs')
    op.drop_index(op.f('ix_vector_deletion_logs_deletion_type'), table_name='vector_deletion_logs')
    op.create_index('idx_vector_deletion_logs_created_at', 'vector_deletion_logs', ['created_at'], unique=False)
    op.create_index('idx_vector_deletion_logs_deletion_type', 'vector_deletion_logs', ['deletion_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vector_deletion_logs_deletion_type', table_name='vector_deletion_logs')
    op.drop_index('idx_vector_deletion_logs_created_at', table_name='vector_deletion_logs')
    op.create_index(op.f('ix_vector_deletion_logs_deletion_type'), 'vector_deletion_logs', ['deletion_type'], unique=False)
    op.create_index(op.f('ix_vector_deletion_logs_created_at'), 'vector_deletion_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_training_sessions_category_id'), 'training_sessions', ['category_id'], unique=False)
    op.alter_column('face_instances', 'quality_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('face_instances', 'detection_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index('ix_face_suggestions_suggested_person_id', table_name='face_suggestions')
    op.drop_index('ix_face_suggestions_status', table_name='face_suggestions')
    op.drop_index('ix_face_suggestions_face_instance_id', table_name='face_suggestions')
    op.drop_table('face_suggestions')
    # ### end Alembic commands ###
