"""Add enhanced face detection session tracking fields

Adds detailed breakdown of face assignment metrics and batch progress tracking:
- faces_assigned_to_persons: Faces matched to known persons
- clusters_created: Number of face clusters created
- suggestions_created: Number of review suggestions created
- current_batch: Current batch being processed
- total_batches: Total batches to process

Revision ID: 974bfe0f68ed
Revises: a1b2c3d4e5f6
Create Date: 2025-12-27 13:41:33.704870

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '974bfe0f68ed'
down_revision: str | Sequence[str] | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns with default values for backward compatibility
    op.add_column('face_detection_sessions', sa.Column('faces_assigned_to_persons', sa.Integer(), nullable=False, server_default='0'))  # noqa: E501
    op.add_column('face_detection_sessions', sa.Column('clusters_created', sa.Integer(), nullable=False, server_default='0'))  # noqa: E501
    op.add_column('face_detection_sessions', sa.Column('suggestions_created', sa.Integer(), nullable=False, server_default='0'))  # noqa: E501
    op.add_column('face_detection_sessions', sa.Column('current_batch', sa.Integer(), nullable=False, server_default='0'))  # noqa: E501
    op.add_column('face_detection_sessions', sa.Column('total_batches', sa.Integer(), nullable=False, server_default='0'))  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face_detection_sessions', 'total_batches')
    op.drop_column('face_detection_sessions', 'current_batch')
    op.drop_column('face_detection_sessions', 'suggestions_created')
    op.drop_column('face_detection_sessions', 'clusters_created')
    op.drop_column('face_detection_sessions', 'faces_assigned_to_persons')
    # ### end Alembic commands ###
