"""make face_suggestions source_face_id nullable

Business context:
Face suggestions can originate from two sources:
1. Face-to-face similarity (source_face_id = the matched face instance)
2. Centroid-based similarity (source_face_id = None, since centroids are not face instances)

This migration makes source_face_id nullable to support centroid-based suggestions,
which currently fail with ForeignKeyViolation when centroid_id is used as source_face_id.

Revision ID: df737c255b50
Revises: cdfb76610d90
Create Date: 2026-02-07 17:27:36.256992

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df737c255b50'
down_revision: str | Sequence[str] | None = 'cdfb76610d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_suggestions', 'source_face_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('uq_face_suggestion_pending'), table_name='face_suggestions', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_ignored_directories_path'), table_name='ignored_directories')
    op.drop_constraint(op.f('uq_ignored_directories_path'), 'ignored_directories', type_='unique')
    op.create_index(op.f('ix_ignored_directories_path'), 'ignored_directories', ['path'], unique=True)
    op.drop_index(op.f('idx_image_assets_gps'), table_name='image_assets', postgresql_where='((gps_latitude IS NOT NULL) AND (gps_longitude IS NOT NULL))')
    op.drop_index(op.f('idx_persons_birth_date'), table_name='persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_persons_birth_date'), 'persons', ['birth_date'], unique=False)
    op.create_index(op.f('idx_image_assets_gps'), 'image_assets', ['gps_latitude', 'gps_longitude'], unique=False, postgresql_where='((gps_latitude IS NOT NULL) AND (gps_longitude IS NOT NULL))')
    op.drop_index(op.f('ix_ignored_directories_path'), table_name='ignored_directories')
    op.create_unique_constraint(op.f('uq_ignored_directories_path'), 'ignored_directories', ['path'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ignored_directories_path'), 'ignored_directories', ['path'], unique=False)
    op.create_index(op.f('uq_face_suggestion_pending'), 'face_suggestions', ['face_instance_id', 'suggested_person_id'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('face_suggestions', 'source_face_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
