"""add_multi_prototype_scoring_fields_to_face_suggestions

Revision ID: f6a668d072bb
Revises: 8d46a4ba4167
Create Date: 2026-01-07 23:30:40.006506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6a668d072bb'
down_revision: Union[str, Sequence[str], None] = '8d46a4ba4167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_suggestions', sa.Column('matching_prototype_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('face_suggestions', sa.Column('prototype_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('face_suggestions', sa.Column('aggregate_confidence', sa.Float(), nullable=True))
    op.add_column('face_suggestions', sa.Column('prototype_match_count', sa.Integer(), nullable=True))
    op.create_index('ix_face_suggestions_aggregate_confidence', 'face_suggestions', ['aggregate_confidence'], unique=False)
    op.alter_column('person_prototypes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_training_subdirectories_path'), table_name='training_subdirectories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_training_subdirectories_path'), 'training_subdirectories', ['path'], unique=False)
    op.alter_column('person_prototypes', 'is_pinned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_face_suggestions_aggregate_confidence', table_name='face_suggestions')
    op.drop_column('face_suggestions', 'prototype_match_count')
    op.drop_column('face_suggestions', 'aggregate_confidence')
    op.drop_column('face_suggestions', 'prototype_scores')
    op.drop_column('face_suggestions', 'matching_prototype_ids')
    # ### end Alembic commands ###
