"""add storage_uploads table

Adds the storage_uploads table for tracking per-asset cloud storage upload
progress within named batches.  Each row represents one ImageAsset being
exported to a remote provider (initially Google Drive) as part of a batch
upload job.  The (batch_id, asset_id) unique constraint makes batch creation
idempotent — re-submitting the same batch is safe and skips existing rows.

Batch lifecycle:
  PENDING   → created, waiting for worker
  UPLOADING → worker has started the file transfer
  COMPLETED → file transferred successfully; remote_file_id populated
  FAILED    → transfer failed; error_message populated; eligible for resume
  CANCELLED → explicitly cancelled by user or system

Revision ID: fcc7bcef2a95
Revises: 34633924ee16
Create Date: 2026-02-17 14:36:29.254111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc7bcef2a95'
down_revision: Union[str, Sequence[str], None] = '34633924ee16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('remote_path', sa.String(length=1024), nullable=True),
    sa.Column('remote_file_id', sa.String(length=256), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['image_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'asset_id', name='uq_storage_upload_batch_asset')
    )
    op.create_index('ix_storage_uploads_asset_id', 'storage_uploads', ['asset_id'], unique=False)
    op.create_index('ix_storage_uploads_batch_id', 'storage_uploads', ['batch_id'], unique=False)
    op.create_index('ix_storage_uploads_batch_status', 'storage_uploads', ['batch_id', 'status'], unique=False)
    op.create_index('ix_storage_uploads_person_id', 'storage_uploads', ['person_id'], unique=False)
    op.create_index('ix_storage_uploads_status', 'storage_uploads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_storage_uploads_status', table_name='storage_uploads')
    op.drop_index('ix_storage_uploads_person_id', table_name='storage_uploads')
    op.drop_index('ix_storage_uploads_batch_status', table_name='storage_uploads')
    op.drop_index('ix_storage_uploads_batch_id', table_name='storage_uploads')
    op.drop_index('ix_storage_uploads_asset_id', table_name='storage_uploads')
    op.drop_table('storage_uploads')
    # ### end Alembic commands ###
